@echo off
echo Starting EduCompass...

echo Starting Backend...
start cmd /k "cd /d %~dp0backend && node server.js"

echo Starting Frontend...
start cmd /k "cd /d %~dp0frontend\educompass && npm start"

echo Both servers starting...
echo Backend  → http://localhost:5000
echo Frontend → http://localhost:3000
